baseURL = "https://blog.storycn.cn/"
# [en, zh-cn, fr, ...] 设置默认的语言
defaultContentLanguage = "zh-cn"
# 网站语言, 仅在这里 CN 大写
languageCode = "zh-CN"
# 是否包括中日韩文字
hasCJKLanguage = true
# 网站标题
title = "时间的朋友"

# 更改使用 Hugo 构建网站时使用的默认主题
theme = "LoveIt"


[params]
  # LoveIt 主题版本
  version = "0.2.X"
  description = "工作中记录的笔记"
  keywords = ["前端", "docker", "javascript", "ArcGIS"]
  defaultTheme = "dark"

  [params.page.code]
    # 是否显示代码块的复制按钮
    copy = true
    # 默认展开显示的代码行数
    maxShownLines = 100
  
  [params.footer]
    enable = true
    # LoveIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
    custom = '时间的朋友'
    # LoveIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
    hugo = false
    # LoveIt 新增 | 0.2.0 是否显示版权信息
    copyright = true
    # LoveIt 新增 | 0.2.0 是否显示作者
    author = true
    # 网站创立年份
    since = 2020
    # ICP 备案信息，仅在中国使用 (支持 HTML 格式)
    icp = ""
    # 许可协议信息 (支持 HTML 格式)
    license = ""
  [params.page.comment]
    enable = false
    # Disqus comment config (https://disqus.com/)
    # Disqus 评论系统设置 (https://disqus.com/)
    [params.page.comment.disqus]
      enable = true
      # Disqus shortname to use Disqus in posts
      # Disqus 的 shortname，用来在文章中启用 Disqus 评论系统
      shortname = ""
    # Gitalk comment config (https://github.com/gitalk/gitalk)
    # Gitalk 评论系统设置 (https://github.com/gitalk/gitalk)
    [params.page.comment.gitalk]
      enable = false
      owner = ""
      repo = ""
      clientId = ""
      clientSecret = ""
    # Valine comment config (https://github.com/xCss/Valine)
    # Valine 评论系统设置 (https://github.com/xCss/Valine)
    [params.page.comment.valine]
      enable = false
      appId = "QGzwQXOqs5JOhN4RGPOkR2mR-MdYXbMMI"
      appKey = "WBmoGyJtbqUswvfLh6L8iEBr"
      placeholder = ""
      avatar = "mp"
      meta= ""
      pageSize = 10
      lang = ""
      visitor = true
      recordIP = true
      highlight = true
      enableQQ = false
      serverURLs = "https://leancloud.hugoloveit.com"
      # emoji data file name, default is "google.yml"
      # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
      # located in "themes/LoveIt/assets/data/emoji/" directory
      # you can store your own data files in the same path under your project:
      # "assets/data/emoji/"
      # emoji 数据文件名称, 默认是 "google.yml"
      # ("apple.yml", "google.yml", "facebook.yml", "twitter.yml")
      # 位于 "themes/LoveIt/assets/data/emoji/" 目录
      # 可以在你的项目下相同路径存放你自己的数据文件:
      # "assets/data/emoji/"
      emoji = ""
    # Facebook comment config (https://developers.facebook.com/docs/plugins/comments)
    # Facebook 评论系统设置 (https://developers.facebook.com/docs/plugins/comments)
    [params.page.comment.facebook]
      enable = false
      width = "100%"
      numPosts = 10
      appId = ""
      languageCode = ""
    # Telegram comments config (https://comments.app/)
    # Telegram comments 评论系统设置 (https://comments.app/)
    [params.page.comment.telegram]
      enable = false
      siteID = ""
      limit = 5
      height = ""
      color = ""
      colorful = true
      dislikes = false
      outlined = false
    # Commento comment config (https://commento.io/)
    # Commento comment 评论系统设置 (https://commento.io/)
    [params.page.comment.commento]
      enable = false
    # Utterances comment config (https://utteranc.es/)
    # Utterances comment 评论系统设置 (https://utteranc.es/)
    [params.page.comment.utterances]
      enable = false
      # owner/repo
      repo = ""
      issueTerm = "pathname"
      label = ""
      lightTheme = "github-light"
      darkTheme = "github-dark"
    # Third-party library config

[author]
  name = "Sparrow"
  email = "east_qiu@outlook.com"
  link = "https://github.com/JunIce"
[menu]
  [[menu.main]]
    identifier = "posts"
    # 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
    pre = ""
    # 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
    post = ""
    name = "文章"
    url = "/posts/"
    # 当你将鼠标悬停在此菜单链接上时, 将显示的标题
    title = ""
    weight = 1
  [[menu.main]]
    identifier = "tags"
    pre = ""
    post = ""
    name = "标签"
    url = "/tags/"
    title = ""
    weight = 2
  [[menu.main]]
    identifier = "categories"
    pre = ""
    post = ""
    name = "分类"
    url = "/categories/"
    title = ""
    weight = 3

# Hugo 解析文档的配置
[markup]
  # 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false
